---
title: "Dev Work"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Dev Work}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, Setup Schedule}
library(magrittr)
library(ggplot2)
library(lubridate)
library(elosport)
library(tidyverse)


'%nin%' <- function(x,y)!('%in%'(x,y))

elo_params <- make_elo_params(0, 25, 2.2, .001, 1, 2.2, 5)

premiership <- list()


files <- list.files(path="../data", pattern="*.csv", full.names=TRUE, recursive=FALSE)
files <- lapply(files, read.csv)
for (i in c(1:10)) {
  dates <- files[[i]]$Date
  dates %<>% ymd()
  files[[i]]$Date <- dates
}
for (i in c(11:length(files))) {
  dates <- files[[i]]$Date
  dates %<>% dmy()
  files[[i]]$Date <- dates
}

schedule <- do.call(rbind, files)
schedule <- schedule[order(schedule$Date), ]

schedule <- schedule[schedule$Away_Score != "[]", ]

schedule$Away_Score %<>% as.numeric()
schedule$Home_Score %<>% as.numeric()
schedule$Home_Team <- gsub('\\s+', '', schedule$Home_Team)
schedule$Away_Team <- gsub('\\s+', '', schedule$Away_Team)

## club names change over time, need to use a manual mapping to standardize
names <- schedule$Home_Team %>% unique %>% sort
proper_names <- c(rep("Bath",2), rep("Bedford",2), rep("Bristol", 3), "Coventry", "Exeter", rep("Gloucester",3), 
                  "Harlequins", rep("Leeds", 2), rep("Leicester", 2), "LiverpoolStHelens", "LondonIrish", "LondonScottish", "Wasps",
                  "LondonWelsh","Moseley", "Harlequins", rep('NewcastleFalcons',2),"NorthamptonSaints","Nottingham","Orrell",
                  "Richmond","RosslynPark","RotherhamTitans","RugbyLions", rep("Sale",2),"Saracens","Wasps","Waterloo","WestHartlepool","WorcesterWarriors")
names_df <- data.frame('rawname' = names, 'proper_names' = proper_names)   

schedule$Home_Team <- names_df$proper_names[match(schedule$Home_Team, names_df$rawname)]
schedule$Away_Team <- names_df$proper_names[match(schedule$Away_Team, names_df$rawname)]
```

```{r, Prepare Teams}
# Create a list containing each team that competes in the league
team_list <- list()
for (team in schedule$Home_Team %>% unique){
  if (schedule[which(schedule$Home_Team == team), ][1, ]$Date < ymd("19880101")) {
    start_elo <- 2500
  } else { # Teams that join the premiership do so from lower tiers, so _should_ have lower elos
    start_elo <- 2250
  }
  team_list[[team]] <- Team$new(team, start_elo)
}
```

```{r, Process Games}
# Now we iterate through each game in the schedule
game_list <- list()

for (row in 1:nrow(schedule)) {
    game_row <- schedule[row, ]
    game_name <- paste0(game_row$Home_Team, game_row$Away_Team, game_row$Date)
    game_list[[game_name]] <- Game$new(game_row$Date,
                            team_list[[game_row$Home_Team]],
                            team_list[[game_row$Away_Team]],
                            game_row$Home_Score,
                            game_row$Away_Score,
                            elo_params,
                            neutral_site = FALSE)
    
    game_list[[game_name]]$process()
}
```

```{r}
league_history <- data.frame()
for (team in team_list){
  league_history %<>% rbind(team$history %>% cbind('Team' = team$alias))
}
league_history <- league_history[order(league_history$Date), ]
league_history$week <- league_history$Date %>% cut('week') %>% ymd()

league_history %<>% mutate(match_week = match(Date, unique(Date)))
```



```{r eval=FALSE, include=FALSE}
library(plotly)
library(htmlwidgets)

myPlot <- plot_ly(league_history, x = ~Date, y = ~Elo, color = ~Team, mode = 'lines')
myPlot
#ggplot(league_history, aes(x=match_week, y=Elo)) +
#  geom_line(aes(color = Team))

```


```{r eval=FALSE, include=FALSE}
library(dygraphs)
library(data.table)

dy_prep <- league_history %>% select(Date, Team, Elo) %>% setDT()

dy_data <- dcast(dy_prep, Date ~ Team, value.var = 'Elo', fun.aggregate = mean, fill = NA) %>% fill(names(.))

dygraph(dy_data) %>% 
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3, highlightSeriesBackgroundAlpha = 0.2)) %>%
  dyLegend(show = "follow", labelsSeparateLines = TRUE) %>%
  dyRangeSelector(dateWindow = c(min(dy_data$Date), max(dy_data$Date)))
```

```{r, highcharts}
library(highcharter) 
league_history$Elo %<>% round(2)
#hc <- highchart(type = "stock") %>%
#  hc_add_series(league_history, type = "line", hcaes(x=Date, y=Elo, group=Team))

hc <- hchart(league_history, 'line', hcaes(x=Date, y=Elo, group=Team))
hc
```

```{d3, data=dy_prep, options=list(color='steelblue')}

```


```{r eval=FALSE, include=FALSE}
## This is an ugly, ugly plot, but it looks as expected - may be better to show as scatter or individual seasons

elo_plot <- ggplot()

for (team in team_list){
  elo_plot <- elo_plot + geom_line(data = team$history, aes(Date, Elo))
}

elo_plot #+ scale_color_manual() #TO BE ADDED, COLOR PER TEAM

```

```{r, Sanity Check}
for (team in team_list){
  team$alias %>% print
  team$elo_score %>% print
}
```
```{r, One Club History}
team_list[['Gloucester']]$history
```

```{r, accuracies}
dates <- sapply(game_list, with, date) %>% as.Date(origin = '1970-01-01')
point_diffs <- sapply(game_list, with, point_diff)
spreads <- sapply(game_list, with, spread)

pred_df <- data.frame(dates, point_diffs, spreads)
pred_df$error <- pred_df$spreads - pred_df$point_diffs

season_2017 <- pred_df[which(pred_df$dates > '2017-06-01' %>% ymd()), ]

ggplot(season_2017, aes(x=dates, y=error)) + geom_line()
```

